create schema sebastian_mejia;

set search_path to sebastian_mejia;

-- =========================
-- tabla: users
-- =========================
create table users (
    id integer generated by default as identity primary key,
    full_name varchar(100) not null,
    email varchar(100) not null unique,
    is_active boolean not null default true,
    created_at timestamp not null default current_timestamp
);

-- =========================
-- tabla: categories
-- =========================
create table categories (
    id integer generated by default as identity primary key,
    name varchar(50) not null unique,
    description text,
    created_at timestamp not null default current_timestamp
);

-- =========================
-- tabla: products
-- =========================
create table products (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    price numeric(10,2) not null default 0,
    stock integer not null default 0,
    created_at timestamp not null default current_timestamp
);

-- =========================
-- tabla: orders
-- =========================
create table orders (
    id integer generated by default as identity primary key,
    order_number varchar(20) not null unique,
    total numeric(10,2) not null default 0,
    status varchar(20) not null default 'PENDING'
);
